services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./:/app